// Package clientgen generates the official TypeScript client from the
// effective OpenAPI document. Plugin operations appear automatically, because
// the document already carries them.
package clientgen

import (
	"fmt"
	"sort"
	"strings"

	"github.com/alternayte/auth-all/openapi"
)

// Header marks the generated file.
const Header = "// Code generated by auth-all client. DO NOT EDIT."

type boundOperation struct {
	method    string
	path      string
	operation *openapi.Operation
}

// Generate returns the TypeScript source of the client.
func Generate(doc *openapi.Document) (string, error) {
	ops, err := collect(doc)
	if err != nil {
		return "", err
	}
	var b strings.Builder
	b.WriteString(Header + "\n")
	b.WriteString("// Source: the effective Auth-All OpenAPI contract.\n\n")
	writeSchemas(&b, doc)
	writeBodies(&b, ops)
	b.WriteString(runtime)
	writeClient(&b, doc, ops)
	return b.String(), nil
}

func collect(doc *openapi.Document) ([]boundOperation, error) {
	var ops []boundOperation
	paths := make([]string, 0, len(doc.Paths))
	for p := range doc.Paths {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		item := doc.Paths[p]
		methods := make([]string, 0, len(item))
		for m := range item {
			methods = append(methods, m)
		}
		sort.Strings(methods)
		for _, m := range methods {
			op := item[m]
			if op == nil || op.Client == nil || op.Client.Method == "" {
				continue
			}
			ops = append(ops, boundOperation{method: strings.ToUpper(m), path: p, operation: op})
		}
	}
	seen := map[string]bool{}
	for _, op := range ops {
		key := op.operation.Client.Namespace + "." + op.operation.Client.Method
		if seen[key] {
			return nil, fmt.Errorf("clientgen: the client binding %q is registered twice", key)
		}
		seen[key] = true
	}
	return ops, nil
}

func writeSchemas(b *strings.Builder, doc *openapi.Document) {
	names := make([]string, 0, len(doc.Components.Schemas))
	for name := range doc.Components.Schemas {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		s := doc.Components.Schemas[name]
		if s.Type == "object" || len(s.Properties) > 0 {
			fmt.Fprintf(b, "export interface %s %s\n\n", name, objectType(s, 0))
			continue
		}
		fmt.Fprintf(b, "export type %s = %s\n\n", name, typeOf(s))
	}
}

func writeBodies(b *strings.Builder, ops []boundOperation) {
	for _, op := range ops {
		schema := bodySchema(op.operation)
		if schema == nil {
			continue
		}
		fmt.Fprintf(b, "export interface %s %s\n\n", bodyTypeName(op.operation), objectType(schema, 0))
	}
}

func bodySchema(op *openapi.Operation) *openapi.Schema {
	if op.RequestBody == nil {
		return nil
	}
	media, ok := op.RequestBody.Content["application/json"]
	if !ok || media.Schema == nil {
		return nil
	}
	if media.Schema.Ref != "" {
		return nil
	}
	return media.Schema
}

func bodyTypeName(op *openapi.Operation) string {
	return exported(op.OperationID) + "Body"
}

func exported(id string) string {
	if id == "" {
		return "Operation"
	}
	return strings.ToUpper(id[:1]) + id[1:]
}

func objectType(s *openapi.Schema, indent int) string {
	pad := strings.Repeat("  ", indent)
	names := make([]string, 0, len(s.Properties))
	for name := range s.Properties {
		names = append(names, name)
	}
	sort.Strings(names)
	required := map[string]bool{}
	for _, r := range s.Required {
		required[r] = true
	}
	var b strings.Builder
	b.WriteString("{\n")
	for _, name := range names {
		optional := "?"
		if required[name] {
			optional = ""
		}
		fmt.Fprintf(&b, "%s  %s%s: %s\n", pad, name, optional, typeOfIndented(s.Properties[name], indent+1))
	}
	if s.AdditionalProperties != nil {
		fmt.Fprintf(&b, "%s  [key: string]: %s\n", pad, typeOfIndented(s.AdditionalProperties, indent+1))
	}
	b.WriteString(pad + "}")
	return b.String()
}

func typeOf(s *openapi.Schema) string { return typeOfIndented(s, 0) }

func typeOfIndented(s *openapi.Schema, indent int) string {
	if s == nil {
		return "unknown"
	}
	var base string
	switch {
	case s.Ref != "":
		base = strings.TrimPrefix(s.Ref, "#/components/schemas/")
	case s.Type == "array":
		base = typeOfIndented(s.Items, indent) + "[]"
	case s.Type == "object" || len(s.Properties) > 0:
		base = objectType(s, indent)
	case s.Type == "string":
		if len(s.Enum) > 0 {
			quoted := make([]string, 0, len(s.Enum))
			for _, e := range s.Enum {
				quoted = append(quoted, "\""+e+"\"")
			}
			base = strings.Join(quoted, " | ")
		} else {
			base = "string"
		}
	case s.Type == "boolean":
		base = "boolean"
	case s.Type == "number" || s.Type == "integer":
		base = "number"
	default:
		base = "unknown"
	}
	if s.Nullable {
		return base + " | null"
	}
	return base
}

func responseType(op *openapi.Operation) string {
	resp, ok := op.Responses["200"]
	if !ok {
		return "void"
	}
	media, ok := resp.Content["application/json"]
	if !ok || media.Schema == nil {
		return "void"
	}
	return typeOf(media.Schema)
}

func pathParams(op *openapi.Operation) []openapi.Parameter {
	var out []openapi.Parameter
	for _, p := range op.Parameters {
		if p.In == "path" {
			out = append(out, p)
		}
	}
	return out
}

func queryParams(op *openapi.Operation) []openapi.Parameter {
	var out []openapi.Parameter
	for _, p := range op.Parameters {
		if p.In == "query" {
			out = append(out, p)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func writeClient(b *strings.Builder, doc *openapi.Document, ops []boundOperation) {
	grouped := map[string][]boundOperation{}
	var namespaces []string
	var root []boundOperation
	for _, op := range ops {
		ns := op.operation.Client.Namespace
		if ns == "" {
			root = append(root, op)
			continue
		}
		if _, ok := grouped[ns]; !ok {
			namespaces = append(namespaces, ns)
		}
		grouped[ns] = append(grouped[ns], op)
	}
	sort.Strings(namespaces)

	fmt.Fprintf(b, "/** The Auth-All API contract version this client was generated from. */\nexport const AUTH_ALL_VERSION = %q\n\n", doc.Info.Version)
	b.WriteString("/** A typed client for the enabled Auth-All API. */\nexport class AuthAllClient {\n")
	b.WriteString("  private readonly http: AuthAllHttp\n\n")
	b.WriteString("  constructor(options: AuthAllClientOptions = {}) {\n    this.http = new AuthAllHttp(options)\n  }\n\n")
	b.WriteString("  /** The absolute base URL of the Auth-All API. */\n  get baseUrl(): string {\n    return this.http.baseUrl\n  }\n")

	for _, op := range root {
		b.WriteString("\n")
		writeMethod(b, op, "  ", op.operation.Client.Method)
	}
	for _, ns := range namespaces {
		fmt.Fprintf(b, "\n  readonly %s = {\n", ns)
		members := grouped[ns]
		sort.Slice(members, func(i, j int) bool {
			return members[i].operation.Client.Method < members[j].operation.Client.Method
		})
		for i, op := range members {
			writeArrowMethod(b, op, "    ")
			if i < len(members)-1 {
				b.WriteString(",\n")
			} else {
				b.WriteString(",\n")
			}
		}
		b.WriteString("  }\n")
	}
	b.WriteString("}\n\n")
	b.WriteString("/** Creates a typed Auth-All client. */\nexport function createAuthClient(options: AuthAllClientOptions = {}): AuthAllClient {\n  return new AuthAllClient(options)\n}\n")
}

// signature returns the argument list and the call body of one operation.
func signature(op boundOperation) (args string, body string, result string) {
	operation := op.operation
	var parts []string
	pathExpr := "`" + strings.ReplaceAll(operation2Path(op), "{", "${") + "`"
	for _, p := range pathParams(operation) {
		parts = append(parts, p.Name+": string")
	}
	if schema := bodySchema(operation); schema != nil {
		parts = append(parts, "body: "+bodyTypeName(operation))
	} else if operation.RequestBody != nil {
		parts = append(parts, "body: unknown")
	}
	query := queryParams(operation)
	queryExpr := "undefined"
	if len(query) > 0 {
		fields := make([]string, 0, len(query))
		for _, p := range query {
			fields = append(fields, p.Name+"?: string")
		}
		parts = append(parts, "query: { "+strings.Join(fields, "; ")+" } = {}")
		queryExpr = "query"
	}
	args = strings.Join(parts, ", ")

	bodyExpr := "undefined"
	if operation.RequestBody != nil {
		bodyExpr = "body"
	}
	if operation.Client.Redirect {
		result = "string"
		body = fmt.Sprintf("this.http.url(%s, %s)", pathExpr, queryExpr)
		return args, body, result
	}
	result = "Promise<" + responseType(operation) + ">"
	body = fmt.Sprintf("this.http.request(%q, %s, %s, %s)", op.method, pathExpr, bodyExpr, queryExpr)
	return args, body, result
}

func operation2Path(op boundOperation) string { return op.path }

func writeMethod(b *strings.Builder, op boundOperation, indent, name string) {
	args, call, result := signature(op)
	if summary := op.operation.Summary; summary != "" {
		fmt.Fprintf(b, "%s/** %s. */\n", indent, summary)
	}
	fmt.Fprintf(b, "%s%s(%s): %s {\n%s  return %s\n%s}\n", indent, name, args, result, indent, call, indent)
}

func writeArrowMethod(b *strings.Builder, op boundOperation, indent string) {
	args, call, result := signature(op)
	call = strings.Replace(call, "this.http", "this.http", 1)
	if summary := op.operation.Summary; summary != "" {
		fmt.Fprintf(b, "%s/** %s. */\n", indent, summary)
	}
	fmt.Fprintf(b, "%s%s: (%s): %s => %s", indent, op.operation.Client.Method, args, result, call)
}

const runtime = `/** Options for the Auth-All client. */
export interface AuthAllClientOptions {
  /** The absolute origin of the application, for example https://app.example.com. */
  baseUrl?: string
  /** The fetch implementation. The global fetch is used by default. */
  fetch?: typeof fetch
  /** The credentials mode. Session cookies need "include" for a cross-origin API. */
  credentials?: RequestCredentials
  /** Extra headers sent with every request. */
  headers?: Record<string, string>
}

/** An Auth-All error with its stable machine-readable code. */
export class AuthAllError extends Error {
  readonly code: string
  readonly status: number

  constructor(code: string, message: string, status: number) {
    super(message)
    this.name = "AuthAllError"
    this.code = code
    this.status = status
  }
}

type QueryValues = Record<string, string | undefined> | undefined

/** The request layer of the generated client. */
export class AuthAllHttp {
  readonly baseUrl: string
  private readonly fetchImpl: typeof fetch
  private readonly credentials: RequestCredentials
  private readonly headers: Record<string, string>

  constructor(options: AuthAllClientOptions = {}) {
    const base = options.baseUrl ?? (typeof location !== "undefined" ? location.origin : "")
    this.baseUrl = base.replace(/\/$/, "")
    this.fetchImpl = options.fetch ?? globalThis.fetch
    this.credentials = options.credentials ?? "include"
    this.headers = options.headers ?? {}
  }

  /** Builds an absolute URL for one API path. */
  url(path: string, query?: QueryValues): string {
    const search = new URLSearchParams()
    for (const [key, value] of Object.entries(query ?? {})) {
      if (value !== undefined) search.set(key, value)
    }
    const suffix = search.toString()
    return this.baseUrl + path + (suffix ? "?" + suffix : "")
  }

  /** Sends one request and maps an Auth-All error to AuthAllError. */
  async request<T>(method: string, path: string, body?: unknown, query?: QueryValues): Promise<T> {
    const headers: Record<string, string> = { Accept: "application/json", ...this.headers }
    if (body !== undefined) headers["Content-Type"] = "application/json"
    const response = await this.fetchImpl(this.url(path, query), {
      method,
      credentials: this.credentials,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    })
    const text = await response.text()
    const payload = text ? JSON.parse(text) : undefined
    if (!response.ok) {
      const error = payload?.error
      throw new AuthAllError(
        error?.code ?? "INTERNAL",
        error?.message ?? "The request failed.",
        response.status,
      )
    }
    return payload as T
  }
}

`
