// Code generated by auth-all client. DO NOT EDIT.
// Source: the effective Auth-All OpenAPI contract.

export interface APIKey {
  createdAt: string
  expiresAt?: string | null
  id: string
  lastUsedAt?: string | null
  name: string
  orgId?: string | null
  revokedAt?: string | null
  role: string
  start: string
  userId?: string
}

export interface APIKeyCreateResponse {
  key: APIKey
  plaintext: string
}

export interface APIKeyListResponse {
  keys: APIKey[]
}

export interface AdminCreateUserResponse {
  temporaryPassword?: string
  user: AdminUser
}

export interface AdminOrganization {
  createdAt: string
  id: string
  name: string
  slug: string
}

export interface AdminOrganizationListResponse {
  nextCursor?: string
  organizations: AdminOrganization[]
}

export interface AdminPasswordResponse {
  temporaryPassword?: string
}

export interface AdminUser {
  createdAt: string
  disabledAt?: string | null
  email: string
  emailVerified: boolean
  id: string
  mustChangePassword: boolean
  name: string
  role: string
  updatedAt: string
}

export interface AdminUserListResponse {
  nextCursor: string
  users: AdminUser[]
}

export interface AdminUserResponse {
  user: AdminUser
}

export interface AuthResponse {
  emailVerificationRequired?: boolean
  mfaRequired?: boolean
  mfaToken?: string
  session: Session | null
  user: User | null
}

export interface DeleteResponse {
  confirmationRequired?: boolean
  success: boolean
}

export interface ErrorResponse {
  error: {
    code: string
    message: string
  }
}

export interface Invitation {
  createdAt: string
  email: string
  expiresAt: string
  id: string
  orgId: string
  role: string
  status: string
}

export interface InvitationCreateResponse {
  invitation: Invitation
  token: string
}

export interface InvitationListResponse {
  invitations: Invitation[]
  nextCursor?: string
}

export interface LinkResponse {
  url: string
}

export interface MagicLinkVerifyResponse {
  redirectTo: string
}

export interface MemberListResponse {
  members: Membership[]
  nextCursor?: string
}

export interface Membership {
  id: string
  joinedAt: string
  orgId: string
  role: string
  status: string
  userId: string
}

export interface MembershipResponse {
  membership: Membership
}

export interface MessageResponse {
  message: string
}

export interface Organization {
  createdAt: string
  extra?: {
  }
  id: string
  name: string
  slug: string
  updatedAt: string
}

export interface OrganizationListResponse {
  nextCursor?: string
  organizations: Organization[]
}

export interface OrganizationResponse {
  organization: Organization
}

export interface OrganizationRole {
  createdAt: string
  name: string
  permissions: string[]
}

export interface OrganizationRoleListResponse {
  roles: OrganizationRole[]
}

export interface OrganizationRoleResponse {
  role: OrganizationRole
}

export interface ProvidersResponse {
  hasPassword: boolean
  providers: {
    accountId: string
    linkedAt: string
    provider: string
  }[]
}

export interface RecoveryCodesResponse {
  recoveryCodes: string[]
}

export interface RevokeAllResponse {
  revoked: number
}

export interface Session {
  createdAt: string
  expiresAt: string
  id: string
  userId: string
}

export interface SessionEntry {
  createdAt: string
  expiresAt: string
  id: string
  lastSeenAt: string
}

export interface SessionListResponse {
  sessions: SessionEntry[]
}

export interface SessionResponse {
  session: Session | null
  user: User | null
}

export interface SuccessResponse {
  success: boolean
}

export interface TOTPConfirmResponse {
  recoveryCodes: string[]
  success: boolean
}

export interface TOTPEnrolResponse {
  secret: string
  uri: string
}

export interface Team {
  createdAt: string
  id: string
  name: string
  orgId: string
  role?: string
}

export interface TeamListResponse {
  teams: Team[]
}

export interface TeamResponse {
  team: Team
}

export interface User {
  createdAt: string
  email: string
  emailVerified: boolean
  id: string
  image: string
  name: string
  role?: string
  updatedAt: string
}

export interface AdminCreateUserBody {
  email: string
  name?: string
  password?: string
  role?: string
  temporaryPassword?: boolean
}

export interface AdminResetUserPasswordBody {
  password?: string
  temporary?: boolean
}

export interface AdminSetUserRoleBody {
  role: string
}

export interface CreateAPIKeyBody {
  expiresAt?: string | null
  name: string
  orgId?: string
  role?: string
}

export interface EmailVerificationSendBody {
  email: string
  redirectTo?: string
}

export interface EmailVerificationVerifyBody {
  token: string
}

export interface EmailChangeBody {
  currentPassword?: string
  newEmail: string
}

export interface EmailChangeVerifyBody {
  token: string
}

export interface MagicLinkSendBody {
  callbackURL?: string
  email: string
}

export interface MagicLinkVerifyBody {
  callbackURL?: string
  token: string
}

export interface CreateOrganizationBody {
  extra?: {
  }
  name: string
  slug: string
}

export interface AcceptOrganizationInvitationBody {
  token: string
}

export interface UpdateOrganizationBody {
  extra?: {
  }
  name?: string
  slug?: string
}

export interface CreateOrganizationInvitationBody {
  email: string
  role?: string
}

export interface UpdateOrganizationMemberBody {
  role?: string
  status?: string
}

export interface CreateOrganizationRoleBody {
  name: string
  permissions: string[]
}

export interface CreateOrganizationTeamBody {
  name: string
  role?: string
}

export interface AddOrganizationTeamMemberBody {
  userId: string
}

export interface PasswordChangeBody {
  currentPassword: string
  newPassword: string
  revokeOtherSessions?: boolean
}

export interface PasswordForgotBody {
  email: string
  redirectTo?: string
}

export interface PasswordResetBody {
  password: string
  token: string
}

export interface RevokeAllSessionsBody {
  includeCurrent?: boolean
}

export interface SignInEmailBody {
  email: string
  password: string
}

export interface SignUpEmailBody {
  email: string
  name?: string
  password: string
}

export interface TotpConfirmBody {
  code: string
}

export interface TotpDisableBody {
  code: string
}

export interface TotpEnrolBody {
}

export interface TotpRecoveryBody {
  code: string
  mfaToken?: string
}

export interface TotpRegenerateRecoveryCodesBody {
  code: string
}

export interface TotpVerifyBody {
  code: string
  mfaToken?: string
}

export interface UserDeleteBody {
  currentPassword?: string
}

export interface UserDeleteVerifyBody {
  token: string
}

/** A value that the client reads before each request. */
export type Provided<T> = T | (() => T | undefined | Promise<T | undefined>)

/** The request that a hook receives. A hook can change the headers. */
export interface AuthAllRequest {
  method: string
  url: string
  headers: Record<string, string>
}

/** Options for the Auth-All client. */
export interface AuthAllClientOptions {
  /** The absolute origin of the application, for example https://app.example.com. */
  baseUrl?: string
  /** The fetch implementation. The global fetch is used by default. */
  fetch?: typeof fetch
  /** The credentials mode. Session cookies need "include" for a cross-origin API. */
  credentials?: RequestCredentials
  /**
   * Extra headers sent with every request. A function runs before each
   * request, so a server that serves many people reads the header of the
   * current one.
   */
  headers?: Provided<Record<string, string>>
  /**
   * The bearer token of the caller. The client sends it as the authorization
   * header. A function runs before each request, so a refreshed token reaches
   * the next call. A browser that uses the session cookie needs none.
   */
  token?: Provided<string>
  /** onRequest runs before each request. It can change the headers. */
  onRequest?: (request: AuthAllRequest) => void | Promise<void>
  /** onResponse runs after each response, including a failed one. */
  onResponse?: (response: Response) => void | Promise<void>
  /**
   * onError runs when a request fails. A global handler sends a person to the
   * sign-in page on UNAUTHORIZED.
   */
  onError?: (error: AuthAllError) => void | Promise<void>
}

/** An Auth-All error with its stable machine-readable code. */
export class AuthAllError extends Error {
  readonly code: string
  readonly status: number

  constructor(code: string, message: string, status: number) {
    super(message)
    this.name = "AuthAllError"
    this.code = code
    this.status = status
  }
}

type QueryValues = Record<string, string | undefined> | undefined

/** resolve reads a value that the caller gave directly or as a function. */
async function resolve<T>(value: Provided<T> | undefined): Promise<T | undefined> {
  if (typeof value === "function") {
    return await (value as () => T | undefined | Promise<T | undefined>)()
  }
  return value
}

/** The request layer of the generated client. */
export class AuthAllHttp {
  readonly baseUrl: string
  private readonly fetchImpl: typeof fetch
  private readonly credentials: RequestCredentials
  private readonly options: AuthAllClientOptions
  private readonly listeners = new Set<() => void>()

  constructor(options: AuthAllClientOptions = {}) {
    const base = options.baseUrl ?? (typeof location !== "undefined" ? location.origin : "")
    this.baseUrl = base.replace(/\/$/, "")
    // A browser fetch needs the global receiver. A plain property read loses
    // it, and the call then throws "Illegal invocation".
    this.fetchImpl = options.fetch ?? ((input, init) => globalThis.fetch(input, init))
    this.credentials = options.credentials ?? "include"
    this.options = options
  }

  /** Builds an absolute URL for one API path. */
  url(path: string, query?: QueryValues): string {
    const search = new URLSearchParams()
    for (const [key, value] of Object.entries(query ?? {})) {
      if (value !== undefined) search.set(key, value)
    }
    const suffix = search.toString()
    return this.baseUrl + path + (suffix ? "?" + suffix : "")
  }

  /**
   * onChange registers a listener that runs after a request that can change
   * the session, which is every request that is no read. A session store uses
   * it to read the session again. It returns the function that removes the
   * listener.
   */
  onChange(listener: () => void): () => void {
    this.listeners.add(listener)
    return () => this.listeners.delete(listener)
  }

  /** Sends one request and maps an Auth-All error to AuthAllError. */
  async request<T>(method: string, path: string, body?: unknown, query?: QueryValues): Promise<T> {
    const extra = (await resolve(this.options.headers)) ?? {}
    const headers: Record<string, string> = { Accept: "application/json", ...extra }
    if (body !== undefined) headers["Content-Type"] = "application/json"
    const token = await resolve(this.options.token)
    if (token) headers["Authorization"] = "Bearer " + token

    const url = this.url(path, query)
    const request: AuthAllRequest = { method, url, headers }
    if (this.options.onRequest) await this.options.onRequest(request)

    const response = await this.fetchImpl(url, {
      method,
      credentials: this.credentials,
      headers: request.headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    })
    if (this.options.onResponse) await this.options.onResponse(response)

    const text = await response.text()
    const payload = text ? JSON.parse(text) : undefined
    if (!response.ok) {
      const failure = payload?.error
      const error = new AuthAllError(
        failure?.code ?? "INTERNAL",
        failure?.message ?? "The request failed.",
        response.status,
      )
      if (this.options.onError) await this.options.onError(error)
      throw error
    }
    // A read changes nothing, so only another method notifies a listener.
    if (method !== "GET" && method !== "HEAD") {
      for (const listener of this.listeners) listener()
    }
    return payload as T
  }
}

/** The Auth-All API contract version this client was generated from. */
export const AUTH_ALL_VERSION = "1.0.0"

/** A typed client for the enabled Auth-All API. */
export class AuthAllClient {
  private readonly http: AuthAllHttp

  constructor(options: AuthAllClientOptions = {}) {
    this.http = new AuthAllHttp(options)
  }

  /** The absolute base URL of the Auth-All API. */
  get baseUrl(): string {
    return this.http.baseUrl
  }

  /**
   * onChange registers a listener that runs after a call that can change
   * the session. A session store uses it to read the session again. It
   * returns the function that removes the listener.
   */
  onChange(listener: () => void): () => void {
    return this.http.onChange(listener)
  }

  /** Return the current session and user. */
  getSession(): Promise<SessionResponse> {
    return this.http.request("GET", `/api/auth/session`, undefined, undefined)
  }

  /** Revoke the current session. */
  signOut(): Promise<SuccessResponse> {
    return this.http.request("POST", `/api/auth/sign-out`, undefined, undefined)
  }

  readonly account = {
    /** Start an explicit provider link. */
    link: (provider: string): Promise<LinkResponse> => this.http.request("POST", `/api/auth/account/link/${provider}`, undefined, undefined),
    /** List the authentication methods of the current user. */
    providers: (): Promise<ProvidersResponse> => this.http.request("GET", `/api/auth/account/providers`, undefined, undefined),
    /** Remove a linked provider. */
    unlink: (provider: string): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/account/unlink/${provider}`, undefined, undefined),
  }

  readonly admin = {
    /** Create a user. */
    createUser: (body: AdminCreateUserBody): Promise<AdminCreateUserResponse> => this.http.request("POST", `/api/auth/admin/users`, body, undefined),
    /** Delete one organization of the application. */
    deleteOrganization: (id: string): Promise<SuccessResponse> => this.http.request("DELETE", `/api/auth/admin/organizations/${id}`, undefined, undefined),
    /** Disable a user. */
    disableUser: (id: string): Promise<AdminUserResponse> => this.http.request("POST", `/api/auth/admin/users/${id}/disable`, undefined, undefined),
    /** Enable a user. */
    enableUser: (id: string): Promise<AdminUserResponse> => this.http.request("POST", `/api/auth/admin/users/${id}/enable`, undefined, undefined),
    /** List every organization of the application. */
    listOrganizations: (query: { cursor?: string; limit?: string } = {}): Promise<AdminOrganizationListResponse> => this.http.request("GET", `/api/auth/admin/organizations`, undefined, query),
    /** List the users. */
    listUsers: (): Promise<AdminUserListResponse> => this.http.request("GET", `/api/auth/admin/users`, undefined, undefined),
    /** Set a new password for a user. */
    resetUserPassword: (id: string, body: AdminResetUserPasswordBody): Promise<AdminPasswordResponse> => this.http.request("POST", `/api/auth/admin/users/${id}/password`, body, undefined),
    /** Set the role of a user. */
    setUserRole: (id: string, body: AdminSetUserRoleBody): Promise<AdminUserResponse> => this.http.request("POST", `/api/auth/admin/users/${id}/role`, body, undefined),
  }

  readonly apiKeys = {
    /** Create an API key. */
    createKey: (body: CreateAPIKeyBody): Promise<APIKeyCreateResponse> => this.http.request("POST", `/api/auth/api-keys`, body, undefined),
    /** List the API keys. */
    listKeys: (): Promise<APIKeyListResponse> => this.http.request("GET", `/api/auth/api-keys`, undefined, undefined),
    /** Revoke an API key. */
    revokeKey: (id: string): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/api-keys/${id}/revoke`, undefined, undefined),
  }

  readonly email = {
    /** Request a change of the email address. */
    change: (body: EmailChangeBody): Promise<MessageResponse> => this.http.request("POST", `/api/auth/email/change`, body, undefined),
    /** Complete a change of the email address. */
    changeVerify: (body: EmailChangeVerifyBody): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/email/change/verify`, body, undefined),
  }

  readonly emailVerification = {
    /** Request an email verification message. */
    send: (body: EmailVerificationSendBody): Promise<MessageResponse> => this.http.request("POST", `/api/auth/email-verification/send`, body, undefined),
    /** Verify an email address with a token. */
    verify: (body: EmailVerificationVerifyBody): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/email-verification/verify`, body, undefined),
  }

  readonly magicLink = {
    /** Send a sign-in link to an email address. */
    send: (body: MagicLinkSendBody): Promise<MessageResponse> => this.http.request("POST", `/api/auth/magic-link/send`, body, undefined),
    /** Complete a sign-in with a link token. */
    verify: (body: MagicLinkVerifyBody): Promise<MagicLinkVerifyResponse> => this.http.request("POST", `/api/auth/magic-link/verify`, body, undefined),
  }

  readonly oauth = {
    /** Start a provider sign-in. */
    authorize: (provider: string, query: { redirect_to?: string } = {}): string => this.http.url(`/api/auth/oauth/${provider}`, query),
    /** Complete a provider sign-in. */
    callback: (provider: string, query: { code?: string; state?: string } = {}): string => this.http.url(`/api/auth/oauth/${provider}/callback`, query),
  }

  readonly organizations = {
    /** Accept one invitation. */
    acceptInvitation: (body: AcceptOrganizationInvitationBody): Promise<MembershipResponse> => this.http.request("POST", `/api/auth/organizations/invitations/accept`, body, undefined),
    /** Put one member in one team. */
    addTeamMember: (id: string, teamId: string, body: AddOrganizationTeamMemberBody): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/organizations/${id}/teams/${teamId}/members`, body, undefined),
    /** End the active organization. */
    clearActive: (): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/organizations/deactivate`, undefined, undefined),
    /** Create an organization. */
    create: (body: CreateOrganizationBody): Promise<OrganizationResponse> => this.http.request("POST", `/api/auth/organizations`, body, undefined),
    /** Declare one custom role. */
    createRole: (id: string, body: CreateOrganizationRoleBody): Promise<OrganizationRoleResponse> => this.http.request("POST", `/api/auth/organizations/${id}/roles`, body, undefined),
    /** Create one team. */
    createTeam: (id: string, body: CreateOrganizationTeamBody): Promise<TeamResponse> => this.http.request("POST", `/api/auth/organizations/${id}/teams`, body, undefined),
    /** Delete one organization. */
    delete: (id: string): Promise<SuccessResponse> => this.http.request("DELETE", `/api/auth/organizations/${id}`, undefined, undefined),
    /** Remove one custom role. */
    deleteRole: (id: string, name: string): Promise<SuccessResponse> => this.http.request("DELETE", `/api/auth/organizations/${id}/roles/${name}`, undefined, undefined),
    /** Remove one team. */
    deleteTeam: (id: string, teamId: string): Promise<SuccessResponse> => this.http.request("DELETE", `/api/auth/organizations/${id}/teams/${teamId}`, undefined, undefined),
    /** Read one organization. */
    get: (id: string): Promise<OrganizationResponse> => this.http.request("GET", `/api/auth/organizations/${id}`, undefined, undefined),
    /** Invite an address into one organization. */
    invite: (id: string, body: CreateOrganizationInvitationBody): Promise<InvitationCreateResponse> => this.http.request("POST", `/api/auth/organizations/${id}/invitations`, body, undefined),
    /** List the organizations of the caller. */
    list: (): Promise<OrganizationListResponse> => this.http.request("GET", `/api/auth/organizations`, undefined, undefined),
    /** List the invitations of one organization. */
    listInvitations: (id: string): Promise<InvitationListResponse> => this.http.request("GET", `/api/auth/organizations/${id}/invitations`, undefined, undefined),
    /** List the members of one organization. */
    listMembers: (id: string): Promise<MemberListResponse> => this.http.request("GET", `/api/auth/organizations/${id}/members`, undefined, undefined),
    /** List the custom roles of one organization. */
    listRoles: (id: string): Promise<OrganizationRoleListResponse> => this.http.request("GET", `/api/auth/organizations/${id}/roles`, undefined, undefined),
    /** List the teams of one organization. */
    listTeams: (id: string): Promise<TeamListResponse> => this.http.request("GET", `/api/auth/organizations/${id}/teams`, undefined, undefined),
    /** Remove one member. */
    removeMember: (id: string, userId: string): Promise<SuccessResponse> => this.http.request("DELETE", `/api/auth/organizations/${id}/members/${userId}`, undefined, undefined),
    /** Take one member out of one team. */
    removeTeamMember: (id: string, teamId: string, userId: string): Promise<SuccessResponse> => this.http.request("DELETE", `/api/auth/organizations/${id}/teams/${teamId}/members/${userId}`, undefined, undefined),
    /** Revoke one pending invitation. */
    revokeInvitation: (id: string, invitationId: string): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/organizations/${id}/invitations/${invitationId}/revoke`, undefined, undefined),
    /** Switch the active organization. */
    setActive: (id: string): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/organizations/${id}/activate`, undefined, undefined),
    /** Change the role or the status of one member. */
    setMember: (id: string, userId: string, body: UpdateOrganizationMemberBody): Promise<MembershipResponse> => this.http.request("PATCH", `/api/auth/organizations/${id}/members/${userId}`, body, undefined),
    /** Update one organization. */
    update: (id: string, body: UpdateOrganizationBody): Promise<OrganizationResponse> => this.http.request("PATCH", `/api/auth/organizations/${id}`, body, undefined),
  }

  readonly password = {
    /** Change the password of the current user. */
    change: (body: PasswordChangeBody): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/password/change`, body, undefined),
    /** Request a password reset message. */
    forgot: (body: PasswordForgotBody): Promise<MessageResponse> => this.http.request("POST", `/api/auth/password/forgot`, body, undefined),
    /** Set a new password with a reset token. */
    reset: (body: PasswordResetBody): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/password/reset`, body, undefined),
  }

  readonly sessions = {
    /** List the sessions of the current user. */
    list: (): Promise<SessionListResponse> => this.http.request("GET", `/api/auth/sessions`, undefined, undefined),
    /** Revoke one session of the current user. */
    revoke: (id: string): Promise<SuccessResponse> => this.http.request("DELETE", `/api/auth/sessions/${id}`, undefined, undefined),
    /** Revoke the other sessions of the current user. */
    revokeAll: (body: RevokeAllSessionsBody): Promise<RevokeAllResponse> => this.http.request("POST", `/api/auth/sessions/revoke-all`, body, undefined),
  }

  readonly signIn = {
    /** Sign in with an email address and a password. */
    email: (body: SignInEmailBody): Promise<AuthResponse> => this.http.request("POST", `/api/auth/sign-in/email`, body, undefined),
  }

  readonly signUp = {
    /** Create an account with an email address and a password. */
    email: (body: SignUpEmailBody): Promise<AuthResponse> => this.http.request("POST", `/api/auth/sign-up/email`, body, undefined),
  }

  readonly totp = {
    /** Complete the enrolment of a second factor. */
    confirm: (body: TotpConfirmBody): Promise<TOTPConfirmResponse> => this.http.request("POST", `/api/auth/totp/confirm`, body, undefined),
    /** Remove the second factor of the current user. */
    disable: (body: TotpDisableBody): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/totp/disable`, body, undefined),
    /** Start the enrolment of a second factor. */
    enrol: (body: TotpEnrolBody): Promise<TOTPEnrolResponse> => this.http.request("POST", `/api/auth/totp/enrol`, body, undefined),
    /** Complete a sign-in with a recovery code. */
    recovery: (body: TotpRecoveryBody): Promise<AuthResponse> => this.http.request("POST", `/api/auth/totp/recovery`, body, undefined),
    /** Replace the recovery codes of the current user. */
    regenerateRecoveryCodes: (body: TotpRegenerateRecoveryCodesBody): Promise<RecoveryCodesResponse> => this.http.request("POST", `/api/auth/totp/recovery-codes/regenerate`, body, undefined),
    /** Complete a sign-in with a second factor. */
    verify: (body: TotpVerifyBody): Promise<AuthResponse> => this.http.request("POST", `/api/auth/totp/verify`, body, undefined),
  }

  readonly user = {
    /** Delete the account of the current user. */
    delete: (body: UserDeleteBody): Promise<DeleteResponse> => this.http.request("POST", `/api/auth/user/delete`, body, undefined),
    /** Complete an account delete with a token. */
    deleteVerify: (body: UserDeleteVerifyBody): Promise<DeleteResponse> => this.http.request("POST", `/api/auth/user/delete/verify`, body, undefined),
  }
}

/** Creates a typed Auth-All client. */
export function createAuthClient(options: AuthAllClientOptions = {}): AuthAllClient {
  return new AuthAllClient(options)
}
