// Code generated by auth-all client. DO NOT EDIT.
// Source: the effective Auth-All OpenAPI contract.

export interface AuthResponse {
  emailVerificationRequired?: boolean
  session: Session | null
  user: User | null
}

export interface ErrorResponse {
  error: {
    code: string
    message: string
  }
}

export interface LinkResponse {
  url: string
}

export interface MessageResponse {
  message: string
}

export interface ProvidersResponse {
  hasPassword: boolean
  providers: {
    accountId: string
    linkedAt: string
    provider: string
  }[]
}

export interface Session {
  createdAt: string
  expiresAt: string
  id: string
  userId: string
}

export interface SessionResponse {
  session: Session | null
  user: User | null
}

export interface SuccessResponse {
  success: boolean
}

export interface User {
  createdAt: string
  email: string
  emailVerified: boolean
  id: string
  image: string
  name: string
  updatedAt: string
}

export interface EmailVerificationSendBody {
  email: string
  redirectTo?: string
}

export interface EmailVerificationVerifyBody {
  token: string
}

export interface MagicLinkSendBody {
  callbackURL?: string
  email: string
}

export interface PasswordForgotBody {
  email: string
  redirectTo?: string
}

export interface PasswordResetBody {
  password: string
  token: string
}

export interface SignInEmailBody {
  email: string
  password: string
}

export interface SignUpEmailBody {
  email: string
  name?: string
  password: string
}

/** Options for the Auth-All client. */
export interface AuthAllClientOptions {
  /** The absolute origin of the application, for example https://app.example.com. */
  baseUrl?: string
  /** The fetch implementation. The global fetch is used by default. */
  fetch?: typeof fetch
  /** The credentials mode. Session cookies need "include" for a cross-origin API. */
  credentials?: RequestCredentials
  /** Extra headers sent with every request. */
  headers?: Record<string, string>
}

/** An Auth-All error with its stable machine-readable code. */
export class AuthAllError extends Error {
  readonly code: string
  readonly status: number

  constructor(code: string, message: string, status: number) {
    super(message)
    this.name = "AuthAllError"
    this.code = code
    this.status = status
  }
}

type QueryValues = Record<string, string | undefined> | undefined

/** The request layer of the generated client. */
export class AuthAllHttp {
  readonly baseUrl: string
  private readonly fetchImpl: typeof fetch
  private readonly credentials: RequestCredentials
  private readonly headers: Record<string, string>

  constructor(options: AuthAllClientOptions = {}) {
    const base = options.baseUrl ?? (typeof location !== "undefined" ? location.origin : "")
    this.baseUrl = base.replace(/\/$/, "")
    this.fetchImpl = options.fetch ?? globalThis.fetch
    this.credentials = options.credentials ?? "include"
    this.headers = options.headers ?? {}
  }

  /** Builds an absolute URL for one API path. */
  url(path: string, query?: QueryValues): string {
    const search = new URLSearchParams()
    for (const [key, value] of Object.entries(query ?? {})) {
      if (value !== undefined) search.set(key, value)
    }
    const suffix = search.toString()
    return this.baseUrl + path + (suffix ? "?" + suffix : "")
  }

  /** Sends one request and maps an Auth-All error to AuthAllError. */
  async request<T>(method: string, path: string, body?: unknown, query?: QueryValues): Promise<T> {
    const headers: Record<string, string> = { Accept: "application/json", ...this.headers }
    if (body !== undefined) headers["Content-Type"] = "application/json"
    const response = await this.fetchImpl(this.url(path, query), {
      method,
      credentials: this.credentials,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    })
    const text = await response.text()
    const payload = text ? JSON.parse(text) : undefined
    if (!response.ok) {
      const error = payload?.error
      throw new AuthAllError(
        error?.code ?? "INTERNAL",
        error?.message ?? "The request failed.",
        response.status,
      )
    }
    return payload as T
  }
}

/** The Auth-All API contract version this client was generated from. */
export const AUTH_ALL_VERSION = "1.0.0"

/** A typed client for the enabled Auth-All API. */
export class AuthAllClient {
  private readonly http: AuthAllHttp

  constructor(options: AuthAllClientOptions = {}) {
    this.http = new AuthAllHttp(options)
  }

  /** The absolute base URL of the Auth-All API. */
  get baseUrl(): string {
    return this.http.baseUrl
  }

  /** Return the current session and user. */
  getSession(): Promise<SessionResponse> {
    return this.http.request("GET", `/api/auth/session`, undefined, undefined)
  }

  /** Revoke the current session. */
  signOut(): Promise<SuccessResponse> {
    return this.http.request("POST", `/api/auth/sign-out`, undefined, undefined)
  }

  readonly account = {
    /** Start an explicit provider link. */
    link: (provider: string): Promise<LinkResponse> => this.http.request("POST", `/api/auth/account/link/${provider}`, undefined, undefined),
    /** List the authentication methods of the current user. */
    providers: (): Promise<ProvidersResponse> => this.http.request("GET", `/api/auth/account/providers`, undefined, undefined),
    /** Remove a linked provider. */
    unlink: (provider: string): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/account/unlink/${provider}`, undefined, undefined),
  }

  readonly emailVerification = {
    /** Request an email verification message. */
    send: (body: EmailVerificationSendBody): Promise<MessageResponse> => this.http.request("POST", `/api/auth/email-verification/send`, body, undefined),
    /** Verify an email address with a token. */
    verify: (body: EmailVerificationVerifyBody): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/email-verification/verify`, body, undefined),
  }

  readonly magicLink = {
    /** Send a sign-in link to an email address. */
    send: (body: MagicLinkSendBody): Promise<MessageResponse> => this.http.request("POST", `/api/auth/magic-link/send`, body, undefined),
    /** Complete a sign-in with a link token. */
    verify: (query: { callbackURL?: string; token?: string } = {}): string => this.http.url(`/api/auth/magic-link/verify`, query),
  }

  readonly oauth = {
    /** Start a provider sign-in. */
    authorize: (provider: string, query: { redirect_to?: string } = {}): string => this.http.url(`/api/auth/oauth/${provider}`, query),
    /** Complete a provider sign-in. */
    callback: (provider: string, query: { code?: string; state?: string } = {}): string => this.http.url(`/api/auth/oauth/${provider}/callback`, query),
  }

  readonly password = {
    /** Request a password reset message. */
    forgot: (body: PasswordForgotBody): Promise<MessageResponse> => this.http.request("POST", `/api/auth/password/forgot`, body, undefined),
    /** Set a new password with a reset token. */
    reset: (body: PasswordResetBody): Promise<SuccessResponse> => this.http.request("POST", `/api/auth/password/reset`, body, undefined),
  }

  readonly signIn = {
    /** Sign in with an email address and a password. */
    email: (body: SignInEmailBody): Promise<AuthResponse> => this.http.request("POST", `/api/auth/sign-in/email`, body, undefined),
  }

  readonly signUp = {
    /** Create an account with an email address and a password. */
    email: (body: SignUpEmailBody): Promise<AuthResponse> => this.http.request("POST", `/api/auth/sign-up/email`, body, undefined),
  }
}

/** Creates a typed Auth-All client. */
export function createAuthClient(options: AuthAllClientOptions = {}): AuthAllClient {
  return new AuthAllClient(options)
}
